library(ggplot2)
library(ggdark)

test_that("geoms are changed appropriately", {
  geoms <- get_geoms()
  lighten_geoms(geoms)
  expect_true(!geoms_are_dark(geoms))
  lighten_geoms(geoms)
  expect_true(!geoms_are_dark(geoms))
  darken_geoms(geoms)
  expect_true(geoms_are_dark(geoms))
  darken_geoms(geoms)
  expect_true(geoms_are_dark(geoms))
  lighten_geoms(geoms)
  expect_true(!geoms_are_dark(geoms))
})
